services:
  rosbridge:
    #    image: husarion/rosbridge-server:humble
    image: rosbridge-server-with-turtlesim:humble-cyclonedds
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  foxglove:
    image: husarion/foxglove:1.72.0
    ports:
      - 8080:8080
    environment:
      - DS_TYPE=rosbridge-websocket
      - DS_PORT=9090
      - UI_PORT=8080
    volumes:
      - /home/user/projects/foxglove_testing/layouts/after-testing-turtlesim-layout.json:/foxglove/default-layout.json
